// For God so loved the world that he gave his only begotten Son,
// that whoever believes in him should not perish but have eternal life.

use anyhow::Result as ResultChirho;
use serde::Deserialize as DeserializeChirho;
use std::fs;
use std::io::Write as WriteChirho;
use std::path::Path as PathChirho;
use std::process::Command as CommandChirho;

const JSON_DIR_CHIRHO: &str = "export-chirho/json-chirho";
const TYPST_OUTPUT_CHIRHO: &str = "export-chirho/bible_chirho.typ";
const PDF_OUTPUT_CHIRHO: &str = "export-chirho/bible_chirho.pdf";
const FONT_DIR_CHIRHO: &str = "site-chirho/fonts";

#[derive(DeserializeChirho)]
struct ManifestChirho {
    total_stats_chirho: StatsChirho,
    books_chirho: Vec<ManifestBookChirho>,
}

#[derive(DeserializeChirho)]
#[allow(dead_code)]
struct ManifestBookChirho {
    book_num_chirho: i64,
    book_name_chirho: String,
    chapters_chirho: Vec<ManifestChapterChirho>,
}

#[derive(DeserializeChirho)]
struct ManifestChapterChirho {
    chapter_chirho: i64,
    file_chirho: String,
    #[allow(dead_code)]
    word_count_chirho: u64,
    #[allow(dead_code)]
    stats_chirho: StatsChirho,
}

#[derive(DeserializeChirho)]
#[allow(dead_code)]
struct StatsChirho {
    total: u64,
    unmodified: u64,
    mismatch: u64,
    not_present: u64,
}

#[derive(DeserializeChirho)]
struct ChapterDataChirho {
    #[allow(dead_code)]
    book_num_chirho: i64,
    #[allow(dead_code)]
    book_name_chirho: String,
    #[allow(dead_code)]
    chapter_chirho: i64,
    verses_chirho: Vec<VerseChirho>,
}

#[derive(DeserializeChirho)]
struct VerseChirho {
    verse_chirho: i64,
    words_chirho: Vec<WordChirho>,
}

#[derive(DeserializeChirho)]
#[allow(dead_code)]
struct WordChirho {
    position_chirho: i64,
    sr_original_chirho: String,
    result_chirho: String,
    status_chirho: String,
    confidence_chirho: f64,
    notes_chirho: Option<String>,
}

/// Escape special Typst characters in text content.
fn escape_typst_chirho(text_chirho: &str) -> String {
    text_chirho
        .replace('\\', "\\\\")
        .replace('#', "\\#")
        .replace('$', "\\$")
        .replace('<', "\\<")
        .replace('>', "\\>")
        .replace('@', "\\@")
        .replace('*', "\\*")
        .replace('_', "\\_")
}

pub fn export_pdf_chirho() -> ResultChirho<()> {
    let manifest_path_chirho = PathChirho::new(JSON_DIR_CHIRHO).join("manifest_chirho.json");
    if !manifest_path_chirho.exists() {
        anyhow::bail!(
            "Manifest not found at {}. Run `export-chirho` first.",
            manifest_path_chirho.display()
        );
    }

    let manifest_text_chirho = fs::read_to_string(&manifest_path_chirho)?;
    let manifest_chirho: ManifestChirho = serde_json::from_str(&manifest_text_chirho)?;

    println!(
        "  Generating Typst source for {} books, {} total words...",
        manifest_chirho.books_chirho.len(),
        manifest_chirho.total_stats_chirho.total
    );

    let mut typ_chirho = fs::File::create(TYPST_OUTPUT_CHIRHO)?;

    // Typst preamble
    writeln!(typ_chirho, r#"// For God so loved the world that he gave his only begotten Son,"#)?;
    writeln!(typ_chirho, r#"// that whoever believes in him should not perish but have eternal life."#)?;
    writeln!(typ_chirho)?;
    writeln!(typ_chirho, r#"#set document(title: "Hebrew Bible — Mikra according to the Masora Accents on Solid Rock", author: "accent-transpose-chirho")"#)?;
    writeln!(typ_chirho, r#"#set page(paper: "a4", margin: (top: 2cm, bottom: 2cm, left: 2cm, right: 2cm))"#)?;
    writeln!(typ_chirho, r#"#set text(font: "Ezra SIL", size: 12pt, dir: rtl, lang: "he")"#)?;
    writeln!(typ_chirho)?;
    writeln!(typ_chirho, r##"#let unmodified-chirho = rgb("#2e7d32")"##)?;
    writeln!(typ_chirho, r##"#let mismatch-chirho = rgb("#e65100")"##)?;
    writeln!(typ_chirho, r##"#let not-present-chirho = rgb("#c62828")"##)?;
    writeln!(typ_chirho)?;
    // Title page
    writeln!(typ_chirho, r#"#align(center + horizon)["#)?;
    writeln!(typ_chirho, r#"  #text(size: 24pt, weight: "bold")[Hebrew Bible]"#)?;
    writeln!(typ_chirho, r#"  #v(0.5cm)"#)?;
    writeln!(typ_chirho, r#"  #text(size: 16pt)[Cantillation Marks Transposed]"#)?;
    writeln!(typ_chirho, r#"  #v(0.3cm)"#)?;
    writeln!(typ_chirho, r#"  #text(size: 12pt)[Mikra according to the Masora (MapM) → Solid Rock Hebrew Bible]"#)?;
    writeln!(typ_chirho, r#"  #v(1cm)"#)?;
    writeln!(typ_chirho, r#"  #text(size: 10pt, fill: gray)[Generated by accent-transpose-chirho]"#)?;
    writeln!(typ_chirho, r#"  #v(0.5cm)"#)?;
    writeln!(typ_chirho, r#"  #text(size: 10pt)["#)?;
    writeln!(typ_chirho, r#"    #text(fill: unmodified-chirho)[■ Matched] #h(0.5cm)"#)?;
    writeln!(typ_chirho, r#"    #text(fill: mismatch-chirho)[■ Mismatch] #h(0.5cm)"#)?;
    writeln!(typ_chirho, r#"    #text(fill: not-present-chirho)[■ Not in MapM]"#)?;
    writeln!(typ_chirho, r#"  ]"#)?;
    writeln!(typ_chirho, r#"]"#)?;
    writeln!(typ_chirho)?;

    for book_chirho in &manifest_chirho.books_chirho {
        writeln!(typ_chirho, r#"#pagebreak()"#)?;
        writeln!(
            typ_chirho,
            r#"#heading(level: 1)[{}]"#,
            escape_typst_chirho(&book_chirho.book_name_chirho)
        )?;
        writeln!(typ_chirho)?;

        for ch_chirho in &book_chirho.chapters_chirho {
            let ch_path_chirho = PathChirho::new(JSON_DIR_CHIRHO).join(&ch_chirho.file_chirho);
            let ch_text_chirho = fs::read_to_string(&ch_path_chirho)?;
            let ch_data_chirho: ChapterDataChirho = serde_json::from_str(&ch_text_chirho)?;

            writeln!(
                typ_chirho,
                r#"#heading(level: 2)[Chapter {}]"#,
                ch_chirho.chapter_chirho
            )?;
            writeln!(typ_chirho)?;

            for verse_chirho in &ch_data_chirho.verses_chirho {
                // Verse number in superscript
                write!(
                    typ_chirho,
                    r#"#super[#text(size: 8pt, fill: gray)[{}]] "#,
                    verse_chirho.verse_chirho
                )?;

                for (i_chirho, word_chirho) in verse_chirho.words_chirho.iter().enumerate() {
                    let color_chirho = match word_chirho.status_chirho.as_str() {
                        "unmodified" | "cantillated" => "unmodified-chirho",
                        "mismatch" => "mismatch-chirho",
                        _ => "not-present-chirho",
                    };

                    let escaped_chirho = escape_typst_chirho(&word_chirho.result_chirho);

                    if i_chirho > 0 {
                        write!(typ_chirho, " ")?;
                    }
                    write!(
                        typ_chirho,
                        r#"#text(fill: {})[{}]"#,
                        color_chirho, escaped_chirho
                    )?;
                }
                writeln!(typ_chirho)?;
            }
            writeln!(typ_chirho)?;
        }

        println!("    {} — {} chapters", book_chirho.book_name_chirho, book_chirho.chapters_chirho.len());
    }

    drop(typ_chirho);
    println!("\n  Typst source written to: {}", TYPST_OUTPUT_CHIRHO);

    // Try to compile with Typst CLI
    let font_dir_chirho = PathChirho::new(FONT_DIR_CHIRHO);

    println!("  Compiling PDF with typst...");
    let result_chirho = CommandChirho::new("typst")
        .args([
            "compile",
            "--font-path",
            &font_dir_chirho.to_string_lossy(),
            TYPST_OUTPUT_CHIRHO,
            PDF_OUTPUT_CHIRHO,
        ])
        .output();

    match result_chirho {
        Ok(output_chirho) => {
            if output_chirho.status.success() {
                println!("  PDF written to: {}", PDF_OUTPUT_CHIRHO);
            } else {
                let stderr_chirho = String::from_utf8_lossy(&output_chirho.stderr);
                eprintln!("  Typst compilation failed:\n{}", stderr_chirho);
                println!("  You can compile manually: typst compile --font-path {} {} {}",
                    font_dir_chirho.display(), TYPST_OUTPUT_CHIRHO, PDF_OUTPUT_CHIRHO);
            }
        }
        Err(_) => {
            println!("  typst CLI not found. Install with: cargo install typst-cli");
            println!("  Then compile manually: typst compile --font-path {} {} {}",
                font_dir_chirho.display(), TYPST_OUTPUT_CHIRHO, PDF_OUTPUT_CHIRHO);
        }
    }

    Ok(())
}
